<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-U3S0M86" failures="1" tests="11" name="test.UserPageTest" time="11.442" errors="0" timestamp="2023-01-24T12:06:38 IST" skipped="10">
  <testcase classname="test.UserPageTest" name="validateBackBtn" time="11.442">
    <failure message="expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:976)
at org.testng.Assert.assertEquals(Assert.java:1010)
at test.UserPageTest.validateBackBtn(UserPageTest.java:132)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateBackBtn -->
  <system-out/>
  <testcase classname="test.UserPageTest" name="validateEditBtn_withInvalidData">
    <skipped/>
  </testcase> <!-- validateEditBtn_withInvalidData -->
  <system-out/>
  <testcase classname="test.UserPageTest" name="validate_save_btn_with_blank_field">
    <skipped/>
  </testcase> <!-- validate_save_btn_with_blank_field -->
  <system-out/>
  <testcase classname="test.UserPageTest" name="validate_save_btn_with_2_mandetory_field">
    <skipped/>
  </testcase> <!-- validate_save_btn_with_2_mandetory_field -->
  <system-out/>
  <testcase classname="test.UserPageTest" name="validateEditBtn_withvalidData_and_Update">
    <skipped/>
  </testcase> <!-- validateEditBtn_withvalidData_and_Update -->
  <system-out/>
  <testcase classname="test.UserPageTest" name="validatePagination">
    <skipped/>
  </testcase> <!-- validatePagination -->
  <system-out/>
  <testcase classname="test.UserPageTest" name="validateSearchBarClrBtn">
    <skipped/>
  </testcase> <!-- validateSearchBarClrBtn -->
  <system-out/>
  <testcase classname="test.UserPageTest" name="validateResetPwd">
    <skipped/>
  </testcase> <!-- validateResetPwd -->
  <system-out/>
  <testcase classname="test.UserPageTest" name="validateDeleteBtn">
    <skipped/>
  </testcase> <!-- validateDeleteBtn -->
  <system-out/>
  <testcase classname="test.UserPageTest" name="validateDropDown">
    <skipped/>
  </testcase> <!-- validateDropDown -->
  <system-out/>
  <testcase classname="test.UserPageTest" name="validateDeleteBtn_Cancel">
    <skipped/>
  </testcase> <!-- validateDeleteBtn_Cancel -->
<testsuite hostname="DESKTOP-7MK4EF7" failures="0" tests="1" name="test.UserPageTest" time="1.647" errors="0" timestamp="2023-01-11T14:06:45 IST" skipped="0">
  <testcase classname="test.UserPageTest" name="user_btn_click" time="1.647"/>
  <system-out/>
</testsuite> <!-- test.UserPageTest -->
